### PR TITLE
Fix crash in chrom 60, windows 7

### LINKED ISSUE #63: several crash wallet
When i testing wallet, several minutes, Web will crash.

### PR DESCRIPTION
**Pull request by andrewsource**
Fix #63 

From @whyka fix crash in exchange_rate, I apply for account and wallet. The reason causes crash is put function convert in title: `title={toT(this.props.balance)}`, so I remove it in rate. account and wallet. Currently, there is no crash in my windows 7, chrome 60. @tranvictor Could you check for OS X

### CODE REVIEW

**Comment by whyka** [comment]
@andrewsource It works like a charm on my Mac. Run several accounts for long time and no crash.
You should remove black list also.

**Comment by whyka** [comment]
@andrewsource Do you know why call function for attribute title in JSX cause problem?

**Comment by andrewsource** [comment]
@whyka I do not know now, It seems this only happens in chrome 60.

**Comment by tranvictor** [comment]
Title is necessary there so people can have a way to see the actual (not rounded) number. Please find another way to avoid inline function calls.

**Comment by andrewsource** [comment]
@tranvictor I've added title after change function **toT**, and there is no crash.

**Comment by tranvictor** [comment]
@andrewsource this is becoming very interesting. So i bet if we want to really know what is wrong we need to dig deeper into BigNumber library. Good job guys @andrewsource @whyka . I will test and merge this soon.

**Pull request merged**
